### ISSUE TITLE
TypeError: expected <type 'basestring'>

### ISSUE THREAD

**Issue by ebob9** [ebob9/cloudgenix_serial_report#1]
```
Building ID->Name lookup table.
Querying APIs.
Parsing Responses.
Building Reports.
Traceback (most recent call last):
  File "./serial_report.py", line 5, in <module>
    cloudgenix_serial_report.go()
  File "/Users/mikekorenbaum/PycharmProjects/cloudgenix_serial_report/cloudgenix_serial_report/__init__.py", line 270, in go
    generate(sdk, specify_filename=args["output"])
  File "/Users/mikekorenbaum/PycharmProjects/cloudgenix_serial_report/cloudgenix_serial_report/__init__.py", line 189, in generate
    ws.column_dimensions[column].width = adjusted_width
  File "/Users/mikekorenbaum/venv/lib/python2.7/site-packages/openpyxl/utils/bound_dictionary.py", line 26, in __getitem__
    setattr(value, self.reference, key)
  File "/Users/mikekorenbaum/venv/lib/python2.7/site-packages/openpyxl/descriptors/base.py", line 44, in __set__
    raise TypeError('expected ' + str(self.expected_type))
TypeError: expected <type 'basestring'>
```

Is seen when generating report.

**Comment by ebob9** [comment]
Issue with `openpyxl`. version 2.6.4 generates this error. If force install v2.5.4, this error goes away.

Workaround for now: `pip install --upgrade openpyxl==2.5.4`
